using System.Collections.Generic;
using System.Text;
using LALR.CC.Schema;
using Microsoft.CodeAnalysis.CSharp;

namespace LALR.CC.SourceGenerators;

/// <summary>
/// Renders a <see cref="GrammarSchema"/> as a C# file containing a static partial
/// class with a populated <c>GrammarSchema</c>. The schema POCO source is shared
/// between this project and the runtime library (linked <c>&lt;Compile Include&gt;</c>
/// in the csproj), so the in-memory shape we read here is the same shape the
/// emitted code constructs at runtime — no parallel DTO mirror to drift.
/// </summary>
internal static class CodeEmitter
{
    public static string Emit(GrammarSchema schema, string namespaceName, string className)
    {
        var sb = new StringBuilder(4096);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by LALR.CC.SourceGenerators. Do not edit.");
        sb.AppendLine("#nullable disable");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using LALR.CC;");
        sb.AppendLine("using LALR.CC.LexicalGrammar;");
        sb.AppendLine("using LALR.CC.Schema;");
        sb.AppendLine();
        sb.Append("namespace ").Append(namespaceName).AppendLine(";");
        sb.AppendLine();
        sb.Append("public static partial class ").Append(className).AppendLine();
        sb.AppendLine("{");
        sb.AppendLine("    public static GrammarSchema Schema { get; } = new()");
        sb.AppendLine("    {");

        EmitSymbols(sb, schema.Symbols);
        EmitProductions(sb, schema.Productions);
        EmitLexer(sb, schema.Lexer);
        EmitActions(sb, schema.Actions);
        EmitColumns(sb, schema.Columns);

        sb.AppendLine("    };");

        // Always emit a no-arg Build() that runs the schema compiler. When the
        // schema has any production-level actions, calling this overload throws
        // at runtime — but we still emit it so users with actions get a hint
        // (the visitor overload in <ClassName>.Visitor.g.cs is the one they
        // actually want, and it shadows this one at the call site for any
        // typed visitor argument). Keeping the no-arg version present means a
        // YAML grammar with no actions is one line away from a working parser:
        //   var (g, lex) = MyGrammar.Build();
        EmitBuild(sb, HasAnyAction(schema));

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static bool HasAnyAction(GrammarSchema schema)
    {
        if (schema.Productions == null) return false;
        foreach (var g in schema.Productions)
        {
            if (g?.Rules == null) continue;
            foreach (var r in g.Rules)
            {
                if (!string.IsNullOrEmpty(r?.Action)) return true;
            }
        }
        return false;
    }

    private static void EmitBuild(StringBuilder sb, bool hasActions)
    {
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Compile <see cref=\"Schema\"/> into the runtime grammar + lexer pair.");
        if (hasActions)
        {
            sb.AppendLine("    /// This overload supplies no production actions, so callers get a");
            sb.AppendLine("    /// schema-compile error if any production names an action. Pass an");
            sb.AppendLine("    /// <c>IVisitor&lt;T&gt;</c> to the typed overload (see Visitor.g.cs) to");
            sb.AppendLine("    /// wire the actions in instead.");
        }
        else
        {
            sb.AppendLine("    /// One-liner replacement for <c>SchemaCompiler.Compile(Schema)</c>;");
            sb.AppendLine("    /// emitted unconditionally so consumer code never has to import");
            sb.AppendLine("    /// <c>LALR.CC.Schema.SchemaCompiler</c> directly.");
        }
        sb.AppendLine("    /// </summary>");
        // global:: + fully-qualified — the consumer's class is often called
        // <c>Grammar</c> too, which would otherwise shadow
        // <see cref="global::LALR.CC.Grammar"/> here and CS0718.
        sb.AppendLine("    public static (global::LALR.CC.Grammar Grammar, Dictionary<string, global::LALR.CC.LexicalGrammar.LexRule[]> Lexer) Build() =>");
        sb.AppendLine("        SchemaCompiler.Compile(Schema);");
    }

    private static void EmitSymbols(StringBuilder sb, List<string> symbols)
    {
        if (symbols == null || symbols.Count == 0)
        {
            sb.AppendLine("        Symbols = { },");
            return;
        }
        sb.Append("        Symbols = { ");
        for (var i = 0; i < symbols.Count; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }
            sb.Append(StringLit(symbols[i]));
        }
        sb.AppendLine(" },");
    }

    private static void EmitProductions(StringBuilder sb, List<ProductionGroupSchema> groups)
    {
        if (groups == null || groups.Count == 0)
        {
            sb.AppendLine("        Productions = { },");
            return;
        }
        sb.AppendLine("        Productions =");
        sb.AppendLine("        {");
        foreach (var group in groups)
        {
            sb.AppendLine("            new()");
            sb.AppendLine("            {");
            // Derivation is a real enum on the schema now (lower-case names in YAML
            // are mapped via WithEnumNamingConvention). Emit the enum value name
            // verbatim — Enum.ToString on a defined value matches the C# identifier.
            sb.Append("                Derivation = Derivation.").Append(group.Derivation).AppendLine(",");
            EmitProductionRules(sb, group.Rules);
            sb.AppendLine("            },");
        }
        sb.AppendLine("        },");
    }

    private static void EmitProductionRules(StringBuilder sb, List<ProductionSchema> rules)
    {
        if (rules == null || rules.Count == 0)
        {
            sb.AppendLine("                Rules = { },");
            return;
        }
        sb.AppendLine("                Rules =");
        sb.AppendLine("                {");
        foreach (var rule in rules)
        {
            sb.Append("                    new() { Lhs = ").Append(StringLit(rule.Lhs)).Append(", Rhs = { ");
            if (rule.Rhs != null)
            {
                for (var i = 0; i < rule.Rhs.Count; i++)
                {
                    if (i > 0)
                    {
                        sb.Append(", ");
                    }
                    sb.Append(StringLit(rule.Rhs[i]));
                }
            }
            sb.Append(" }");
            if (!string.IsNullOrEmpty(rule.Action))
            {
                sb.Append(", Action = ").Append(StringLit(rule.Action));
            }
            sb.AppendLine(" },");
        }
        sb.AppendLine("                },");
    }

    private static void EmitLexer(StringBuilder sb, Dictionary<string, List<LexRuleSchema>> lexer)
    {
        if (lexer == null || lexer.Count == 0)
        {
            sb.AppendLine("        Lexer = { },");
            return;
        }
        sb.AppendLine("        Lexer =");
        sb.AppendLine("        {");
        foreach (var kv in lexer)
        {
            sb.Append("            [").Append(StringLit(kv.Key)).AppendLine("] = new List<LexRuleSchema>");
            sb.AppendLine("            {");
            EmitLexRules(sb, kv.Value);
            sb.AppendLine("            },");
        }
        sb.AppendLine("        },");
    }

    private static void EmitLexRules(StringBuilder sb, List<LexRuleSchema> rules)
    {
        if (rules == null)
        {
            return;
        }
        foreach (var rule in rules)
        {
            sb.Append("                new() { Symbol = ").Append(StringLit(rule.Symbol))
              .Append(", Match = ").Append(StringLit(rule.Match));
            if (!string.IsNullOrEmpty(rule.Push))
            {
                sb.Append(", Push = ").Append(StringLit(rule.Push));
            }
            if (rule.Pop)
            {
                sb.Append(", Pop = true");
            }
            if (!string.IsNullOrEmpty(rule.Action))
            {
                sb.Append(", Action = ").Append(StringLit(rule.Action));
            }
            sb.AppendLine(" },");
        }
    }

    private static void EmitActions(StringBuilder sb, ActionsSchema actions)
    {
        if (actions == null || string.IsNullOrEmpty(actions.ClassName))
        {
            return;
        }
        sb.AppendLine("        Actions = new ActionsSchema");
        sb.AppendLine("        {");
        sb.Append("            ClassName = ").Append(StringLit(actions.ClassName)).AppendLine(",");
        sb.AppendLine("        },");
    }

    /// <summary>
    /// Emit the schema's <c>Columns</c> setting verbatim — only when the YAML
    /// explicitly specified it. The runtime <see cref="GrammarSchema.Columns"/>
    /// is nullable; absence means "consumer decides", and the lexer ctor's
    /// own default (<c>Codepoints</c>) takes over.
    /// </summary>
    private static void EmitColumns(StringBuilder sb, LALR.CC.LexicalGrammar.ColumnMode? columns)
    {
        if (columns == null)
        {
            return;
        }
        sb.Append("        Columns = global::LALR.CC.LexicalGrammar.ColumnMode.")
          .Append(columns.Value).AppendLine(",");
    }

    /// <summary>
    /// Produce a C# string literal, including surrounding quotes and full escaping.
    /// Uses Roslyn's SymbolDisplay so we get the same handling the language itself
    /// applies (verbatim / interpolated / control chars / etc).
    /// </summary>
    private static string StringLit(string value)
    {
        return SymbolDisplay.FormatLiteral(value ?? "", quote: true);
    }
}
