using System.Collections.Generic;
using System.Text;
using CodeProject.Syntax.LALR.Schema;

namespace CodeProject.Syntax.LALR.SourceGenerators;

/// <summary>
/// Phase 3 / slice 1: emits a typed record per <see cref="ProductionSchema"/> whose
/// <c>Action</c> is non-empty. Records are nested inside the same
/// <c>public static partial class &lt;ClassName&gt;</c> the schema-emitter targets, so
/// the user-visible surface is one host type with both <c>Schema</c> and the AST
/// records hanging off it. The records take <see cref="LALR.Item"/>-typed positional
/// arguments for now — slice 2 (visitor) is when we'd start typing children to other
/// generated records; doing it here would lock the cross-reference shape in before
/// we know what the visitor wants.
/// </summary>
/// <remarks>
/// Arity rule: an <c>action</c> name may appear on multiple productions, but every
/// occurrence must share the same RHS arity. Same name + same arity coalesces to one
/// record (the visitor in slice 2 will dispatch through a single method). Same name +
/// different arity is reported as <see cref="ArityConflictError"/>; the caller turns
/// it into a Roslyn diagnostic (<c>LALR0002</c>).
/// </remarks>
internal static class AstEmitter
{
    public readonly struct ArityConflictError
    {
        public ArityConflictError(string actionName, int firstArity, int secondArity)
        {
            ActionName = actionName;
            FirstArity = firstArity;
            SecondArity = secondArity;
        }

        public string ActionName { get; }
        public int FirstArity { get; }
        public int SecondArity { get; }

        public string Message =>
            $"action '{ActionName}' is used with {FirstArity} RHS symbol(s) on one production "
            + $"and {SecondArity} on another; same action name must always have the same arity";
    }

    public readonly struct Result
    {
        public Result(string? source, IReadOnlyList<ArityConflictError> errors)
        {
            Source = source;
            Errors = errors;
        }

        /// <summary>The emitted source, or null when the schema declares no actions.</summary>
        public string? Source { get; }
        public IReadOnlyList<ArityConflictError> Errors { get; }
    }

    public static Result Emit(GrammarSchema schema, string namespaceName, string className)
    {
        // Collect distinct (action → arity) pairs in the order they first appear.
        // Walking productions in source order means the emitted record list is stable
        // for a given input, which keeps the generator deterministic.
        var actionArities = new Dictionary<string, int>(System.StringComparer.Ordinal);
        var actionsInOrder = new List<string>();
        var errors = new List<ArityConflictError>();

        if (schema.Productions != null)
        {
            foreach (var group in schema.Productions)
            {
                if (group?.Rules == null)
                {
                    continue;
                }
                foreach (var rule in group.Rules)
                {
                    if (rule == null || string.IsNullOrEmpty(rule.Action))
                    {
                        continue;
                    }
                    var action = rule.Action;
                    var arity = rule.Rhs?.Count ?? 0;
                    if (actionArities.TryGetValue(action, out var existing))
                    {
                        if (existing != arity)
                        {
                            errors.Add(new ArityConflictError(action, existing, arity));
                        }
                        // Same action + same arity: already recorded, skip.
                        continue;
                    }
                    actionArities[action] = arity;
                    actionsInOrder.Add(action);
                }
            }
        }

        if (actionsInOrder.Count == 0)
        {
            // No actions → no AST file. Schema-only emit covers everything.
            return new Result(null, errors);
        }

        var sb = new StringBuilder(2048);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by CodeProject.Syntax.LALR.SourceGenerators. Do not edit.");
        sb.AppendLine("#nullable disable");
        sb.AppendLine("using CodeProject.Syntax.LALR.LexicalGrammar;");
        sb.AppendLine();
        sb.Append("namespace ").Append(namespaceName).AppendLine(";");
        sb.AppendLine();
        sb.Append("public static partial class ").Append(className).AppendLine();
        sb.AppendLine("{");

        for (var i = 0; i < actionsInOrder.Count; i++)
        {
            if (i > 0)
            {
                sb.AppendLine();
            }
            EmitRecord(sb, actionsInOrder[i], actionArities[actionsInOrder[i]]);
        }

        sb.AppendLine("}");
        return new Result(sb.ToString(), errors);
    }

    private static void EmitRecord(StringBuilder sb, string actionName, int arity)
    {
        var typeName = PascalCase(actionName);
        sb.Append("    public sealed record ").Append(typeName).Append('(');
        for (var i = 0; i < arity; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }
            sb.Append("Item Arg").Append(i);
        }
        sb.AppendLine(");");
    }

    /// <summary>
    /// Conservative PascalCase: capitalise first letter, leave the rest alone. Action
    /// names in the schema are expected to be camelCase identifiers already (matching
    /// the dictionary keys passed to <c>SchemaCompiler.Compile</c>); we just bump the
    /// first character so the emitted record name follows C# conventions.
    /// </summary>
    private static string PascalCase(string name)
    {
        if (string.IsNullOrEmpty(name))
        {
            return name;
        }
        if (char.IsUpper(name[0]))
        {
            return name;
        }
        return char.ToUpperInvariant(name[0]) + name.Substring(1);
    }
}
