using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis.CSharp;

namespace CodeProject.Syntax.LALR.SourceGenerators;

/// <summary>
/// Renders a <see cref="YamlGrammarSchema"/> as a C# file containing a static
/// partial class with a populated <c>GrammarSchema</c>. The output references the
/// runtime library's types (<c>CodeProject.Syntax.LALR.Schema.GrammarSchema</c>,
/// <c>Derivation</c>, <c>LexRuleSchema</c>, …) but never instantiates them inside
/// the generator — the netstandard2.0 generator can't load net10.0 assemblies.
/// </summary>
internal static class CodeEmitter
{
    public static string Emit(YamlGrammarSchema schema, string namespaceName, string className)
    {
        var sb = new StringBuilder(4096);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by CodeProject.Syntax.LALR.SourceGenerators. Do not edit.");
        sb.AppendLine("#nullable disable");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using CodeProject.Syntax.LALR;");
        sb.AppendLine("using CodeProject.Syntax.LALR.Schema;");
        sb.AppendLine();
        sb.Append("namespace ").Append(namespaceName).AppendLine(";");
        sb.AppendLine();
        sb.Append("public static partial class ").Append(className).AppendLine();
        sb.AppendLine("{");
        sb.AppendLine("    public static GrammarSchema Schema { get; } = new()");
        sb.AppendLine("    {");

        EmitSymbols(sb, schema.Symbols);
        EmitProductions(sb, schema.Productions);
        EmitLexer(sb, schema.Lexer);
        EmitActions(sb, schema.Actions);

        sb.AppendLine("    };");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitSymbols(StringBuilder sb, List<string> symbols)
    {
        if (symbols == null || symbols.Count == 0)
        {
            sb.AppendLine("        Symbols = { },");
            return;
        }
        sb.Append("        Symbols = { ");
        for (var i = 0; i < symbols.Count; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }
            sb.Append(StringLit(symbols[i]));
        }
        sb.AppendLine(" },");
    }

    private static void EmitProductions(StringBuilder sb, List<YamlProductionGroup> groups)
    {
        if (groups == null || groups.Count == 0)
        {
            sb.AppendLine("        Productions = { },");
            return;
        }
        sb.AppendLine("        Productions =");
        sb.AppendLine("        {");
        foreach (var group in groups)
        {
            sb.AppendLine("            new()");
            sb.AppendLine("            {");
            // Phase 2D will validate; here we trust the YAML loader's input. Unrecognised
            // derivation strings get coerced to None — runtime will compile fine; the
            // generator-level validation pass surfaces a diagnostic.
            _ = YamlGrammarLoader.TryParseDerivation(group.Derivation, out var derivationName);
            if (string.IsNullOrEmpty(derivationName))
            {
                derivationName = "None";
            }
            sb.Append("                Derivation = Derivation.").Append(derivationName).AppendLine(",");
            EmitProductionRules(sb, group.Rules);
            sb.AppendLine("            },");
        }
        sb.AppendLine("        },");
    }

    private static void EmitProductionRules(StringBuilder sb, List<YamlProduction> rules)
    {
        if (rules == null || rules.Count == 0)
        {
            sb.AppendLine("                Rules = { },");
            return;
        }
        sb.AppendLine("                Rules =");
        sb.AppendLine("                {");
        foreach (var rule in rules)
        {
            sb.Append("                    new() { Lhs = ").Append(StringLit(rule.Lhs)).Append(", Rhs = { ");
            if (rule.Rhs != null)
            {
                for (var i = 0; i < rule.Rhs.Count; i++)
                {
                    if (i > 0)
                    {
                        sb.Append(", ");
                    }
                    sb.Append(StringLit(rule.Rhs[i]));
                }
            }
            sb.Append(" }");
            if (!string.IsNullOrEmpty(rule.Action))
            {
                sb.Append(", Action = ").Append(StringLit(rule.Action));
            }
            sb.AppendLine(" },");
        }
        sb.AppendLine("                },");
    }

    private static void EmitLexer(StringBuilder sb, Dictionary<string, List<YamlLexRule>> lexer)
    {
        if (lexer == null || lexer.Count == 0)
        {
            sb.AppendLine("        Lexer = { },");
            return;
        }
        sb.AppendLine("        Lexer =");
        sb.AppendLine("        {");
        foreach (var kv in lexer)
        {
            sb.Append("            [").Append(StringLit(kv.Key)).AppendLine("] = new List<LexRuleSchema>");
            sb.AppendLine("            {");
            EmitLexRules(sb, kv.Value);
            sb.AppendLine("            },");
        }
        sb.AppendLine("        },");
    }

    private static void EmitLexRules(StringBuilder sb, List<YamlLexRule> rules)
    {
        if (rules == null)
        {
            return;
        }
        foreach (var rule in rules)
        {
            sb.Append("                new() { Symbol = ").Append(StringLit(rule.Symbol))
              .Append(", Match = ").Append(StringLit(rule.Match));
            if (!string.IsNullOrEmpty(rule.Push))
            {
                sb.Append(", Push = ").Append(StringLit(rule.Push));
            }
            if (rule.Pop)
            {
                sb.Append(", Pop = true");
            }
            if (!string.IsNullOrEmpty(rule.Action))
            {
                sb.Append(", Action = ").Append(StringLit(rule.Action));
            }
            sb.AppendLine(" },");
        }
    }

    private static void EmitActions(StringBuilder sb, YamlActions? actions)
    {
        if (actions == null || string.IsNullOrEmpty(actions.ClassName))
        {
            return;
        }
        sb.AppendLine("        Actions = new ActionsSchema");
        sb.AppendLine("        {");
        sb.Append("            ClassName = ").Append(StringLit(actions.ClassName)).AppendLine(",");
        sb.AppendLine("        },");
    }

    /// <summary>
    /// Produce a C# string literal, including surrounding quotes and full escaping.
    /// Uses Roslyn's SymbolDisplay so we get the same handling the language itself
    /// applies (verbatim / interpolated / control chars / etc).
    /// </summary>
    private static string StringLit(string? value)
    {
        return SymbolDisplay.FormatLiteral(value ?? "", quote: true);
    }
}
