using System.Collections.Generic;
using System.Text;
using CodeProject.Syntax.LALR.Schema;

namespace CodeProject.Syntax.LALR.SourceGenerators;

/// <summary>
/// Phase 3 / slice 2: emits a typed visitor interface and a wiring helper that
/// adapts visitor calls back to the <c>Func&lt;int, Item[], object&gt;</c> contract
/// that <c>SchemaCompiler.Compile(schema, actions)</c> already consumes. Users
/// implement <c>IVisitor</c> with their semantic logic; the generated
/// <c>BuildActions</c> packs visitor methods into the actions dictionary.
/// </summary>
/// <remarks>
/// The visitor's method names are the PascalCased action name (so they match the
/// AST record name from <see cref="AstEmitter"/>). The dictionary keys are the
/// original camelCase action strings (what <c>SchemaCompiler</c> looks up). Every
/// visitor method returns <c>object</c> for now — that's the existing rewriter
/// contract and gives users full freedom to return their own AST shape (including
/// the generated record). A typed-return refinement can come later.
/// </remarks>
internal static class VisitorEmitter
{
    public static string? Emit(GrammarSchema schema, string namespaceName, string className)
    {
        var actions = CollectActions(schema);
        if (actions.Count == 0)
        {
            return null;
        }

        var sb = new StringBuilder(2048);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by CodeProject.Syntax.LALR.SourceGenerators. Do not edit.");
        sb.AppendLine("#nullable disable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using CodeProject.Syntax.LALR;");
        sb.AppendLine("using CodeProject.Syntax.LALR.LexicalGrammar;");
        sb.AppendLine("using CodeProject.Syntax.LALR.Schema;");
        sb.AppendLine();
        sb.Append("namespace ").Append(namespaceName).AppendLine(";");
        sb.AppendLine();
        sb.Append("public static partial class ").Append(className).AppendLine();
        sb.AppendLine("{");

        EmitVisitorInterface(sb, actions);
        sb.AppendLine();
        EmitBuildActions(sb, actions);
        sb.AppendLine();
        EmitBuildWithVisitor(sb);

        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// Emits a typed-visitor overload of <c>Build</c> that pairs with the
    /// no-arg version emitted by <see cref="CodeEmitter"/>. Only present when
    /// the schema has at least one action (this whole file is suppressed
    /// otherwise), so the call site is consistent: actions present ⇒ pass a
    /// visitor; no actions ⇒ no-arg.
    /// </summary>
    private static void EmitBuildWithVisitor(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Compile <see cref=\"Schema\"/> with the supplied visitor's action");
        sb.AppendLine("    /// dictionary in one call. Equivalent to");
        sb.AppendLine("    /// <c>SchemaCompiler.Compile(Schema, BuildActions(visitor))</c> but");
        sb.AppendLine("    /// emitted alongside the schema so consumer code never has to import");
        sb.AppendLine("    /// <see cref=\"SchemaCompiler\"/> directly.");
        sb.AppendLine("    /// </summary>");
        // global:: + fully-qualified — see CodeEmitter.EmitBuild for why.
        sb.AppendLine("    public static (global::CodeProject.Syntax.LALR.Grammar Grammar, Dictionary<string, global::CodeProject.Syntax.LALR.LexicalGrammar.LexRule[]> Lexer) Build<T>(IVisitor<T> visitor) =>");
        sb.AppendLine("        SchemaCompiler.Compile(Schema, BuildActions(visitor));");
    }

    private readonly struct ActionInfo
    {
        public ActionInfo(string actionName, string methodName, int arity)
        {
            ActionName = actionName;
            MethodName = methodName;
            Arity = arity;
        }
        public string ActionName { get; }
        public string MethodName { get; }
        public int Arity { get; }
    }

    private static List<ActionInfo> CollectActions(GrammarSchema schema)
    {
        // Walk productions in source order, dedupe by action name. Arity conflicts are
        // already reported by AstEmitter (LALR0002) — here we just take the first
        // arity we see and move on, so the visitor still emits a coherent surface
        // even when AstEmitter is reporting a parallel error. The build will fail
        // either way; the goal is to avoid cascading "method not found" noise on top
        // of the real diagnostic.
        var seen = new Dictionary<string, ActionInfo>(System.StringComparer.Ordinal);
        var result = new List<ActionInfo>();
        if (schema.Productions == null)
        {
            return result;
        }
        foreach (var group in schema.Productions)
        {
            if (group?.Rules == null)
            {
                continue;
            }
            foreach (var rule in group.Rules)
            {
                if (rule == null || string.IsNullOrEmpty(rule.Action))
                {
                    continue;
                }
                var action = rule.Action;
                if (seen.ContainsKey(action))
                {
                    continue;
                }
                var info = new ActionInfo(action, PascalCase(action), rule.Rhs?.Count ?? 0);
                seen[action] = info;
                result.Add(info);
            }
        }
        return result;
    }

    private static void EmitVisitorInterface(StringBuilder sb, List<ActionInfo> actions)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Semantic-action surface. One <c>Visit</c> overload per record emitted by the");
        sb.AppendLine("    /// AST emitter (one record per distinct production action). The type parameter");
        sb.AppendLine("    /// <typeparamref name=\"T\"/> is the visitor's return type — when every method");
        sb.AppendLine("    /// returns the same shape (e.g. <c>int</c> for an evaluator) the visitor signature");
        sb.AppendLine("    /// stays honest; pass <c>IVisitor&lt;object&gt;</c> if methods need to return");
        sb.AppendLine("    /// different shapes per production. Implementations are wired into the parser via");
        sb.AppendLine("    /// <see cref=\"BuildActions\"/>, which constructs the matching record from the");
        sb.AppendLine("    /// parser's reduction frame and dispatches by C# overload resolution.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public interface IVisitor<out T>");
        sb.AppendLine("    {");
        for (var i = 0; i < actions.Count; i++)
        {
            var a = actions[i];
            sb.Append("        T Visit(").Append(a.MethodName).AppendLine(" node);");
        }
        sb.AppendLine("    }");
    }

    private static void EmitBuildActions(StringBuilder sb, List<ActionInfo> actions)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Adapt a typed <see cref=\"IVisitor{T}\"/> implementation into the action");
        sb.AppendLine("    /// dictionary that <c>CodeProject.Syntax.LALR.Schema.SchemaCompiler.Compile(schema, actions)</c>");
        sb.AppendLine("    /// consumes. Each entry constructs the AST record for that production from the");
        sb.AppendLine("    /// parser's <c>Item[]</c> reduction frame, then dispatches to the matching");
        sb.AppendLine("    /// <c>Visit</c> overload on the visitor; the visitor's typed return is boxed to");
        sb.AppendLine("    /// <c>object</c> for storage on <c>Item.Content</c> and unboxed by the consumer.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IReadOnlyDictionary<string, Func<int, Item[], object>> BuildActions<T>(IVisitor<T> visitor)");
        sb.AppendLine("    {");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(visitor);");
        sb.AppendLine("        return new Dictionary<string, Func<int, Item[], object>>(StringComparer.Ordinal)");
        sb.AppendLine("        {");
        foreach (var a in actions)
        {
            sb.Append("            [\"").Append(EscapeStringContent(a.ActionName)).Append("\"] = (lhs, args) => visitor.Visit(new ")
              .Append(a.MethodName).Append('(');
            for (var j = 0; j < a.Arity; j++)
            {
                if (j > 0)
                {
                    sb.Append(", ");
                }
                sb.Append("args[").Append(j).Append(']');
            }
            sb.AppendLine(")),");
        }
        sb.AppendLine("        };");
        sb.AppendLine("    }");
    }

    private static string PascalCase(string name)
    {
        if (string.IsNullOrEmpty(name))
        {
            return name;
        }
        if (char.IsUpper(name[0]))
        {
            return name;
        }
        return char.ToUpperInvariant(name[0]) + name.Substring(1);
    }

    /// <summary>
    /// Escape control characters and quotes for safe inclusion in a C# verbatim
    /// <c>"…"</c> literal. We don't accept arbitrary user input (action names come
    /// from YAML keys typed by the schema author), but defence-in-depth is cheap.
    /// </summary>
    private static string EscapeStringContent(string value)
    {
        if (string.IsNullOrEmpty(value))
        {
            return value;
        }
        var sb = new StringBuilder(value.Length);
        foreach (var c in value)
        {
            switch (c)
            {
                case '\\': sb.Append("\\\\"); break;
                case '"': sb.Append("\\\""); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default: sb.Append(c); break;
            }
        }
        return sb.ToString();
    }
}
